#!/usr/bin/env bash
# Displays best school 10 times but for the 10 time
# Displays best school and then hi on the next line.
# using only while loops and if statement.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done

